### ISSUE TITLE
Import error yaml2nxdl

### ISSUE THREAD

**Issue by cmmngr** [nomad-coe/nomad-parser-nexus#51]
Lines 37-39 in yaml2nxdl.py cause an import error: 
`ImportError: attempted relative import with no known parent package`
It seems that the imports were changed recently: https://github.com/nomad-coe/nomad-parser-nexus/pull/39

**Comment by shabihsherjeel** [comment]
Are you running this as ./yaml2nxdl.py from its directory? I was able to reproduce this error when I ran it like this as well. I am not sure how it should really behave in that scenario. But I will suggest to do a pip install on the whole package. Then you can just type "yaml2nxdl" from anywhere in your terminal and it should work. 

@domna is there any specific reason to switch to relative imports instead of absolute ones? I find absolute imports usually much better to read and work with. If you're okay with it, we can switch it back? Or let me know if I'm missing something.

**Comment by domna** [comment]
@shabihsherjeel No there is actually no specific reason to it. I somehow changed it due to the removal of `sys.path.insert` in the init file because I thought the absolute paths would be wrong then, but I think they are actually not affected by it.

I agree we should change it back to absolute ones as it is the convention in the rest of the project, too.
